version: "3.9"

services:
  babyagi:
    build: ./
    container_name: babyagi
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - "./:/app"
    stdin_open: true
    tty: true
    ulimits:
      memlock: -1
